import io
import os
from datetime import datetime

def export_txt(bullet_points, paragraph, keywords, original_word_count, summary_word_count):
    """Generate plain text summary."""
    lines = []
    lines.append("=" * 60)
    lines.append("SCHOLARSUM - DOCUMENT SUMMARY")
    lines.append(f"Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Original words : {original_word_count:,}")
    lines.append(f"Summary words  : {summary_word_count:,}")
    compression = round((1 - summary_word_count / original_word_count) * 100)
    lines.append(f"Compression    : {compression}%")
    lines.append("")
    lines.append("-" * 60)
    lines.append("PARAGRAPH SUMMARY")
    lines.append("-" * 60)
    lines.append(paragraph)
    lines.append("")
    lines.append("-" * 60)
    lines.append("KEY TAKEAWAYS")
    lines.append("-" * 60)
    for i, point in enumerate(bullet_points, 1):
        lines.append(f"{i}. {point}")
    lines.append("")
    lines.append("-" * 60)
    lines.append("KEY TERMS")
    lines.append("-" * 60)
    lines.append(", ".join(w for w, _ in keywords))
    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by ScholarSum - Cambrian College NLP Capstone 2026")
    return "\n".join(lines)


def export_docx(bullet_points, paragraph, keywords, original_word_count, summary_word_count):
    """Generate a formatted Word document."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
    except ImportError:
        raise Exception("python-docx not installed. Run: pip install python-docx")

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)

    # Title
    title = doc.add_heading('ScholarSum', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.runs[0]
    run.font.color.rgb = RGBColor(0x1a, 0x3a, 0x5c)

    subtitle = doc.add_paragraph('Intelligent Academic Document Summary')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.color.rgb = RGBColor(0x37, 0x6b, 0xa8)
    subtitle.runs[0].font.size = Pt(12)

    date_para = doc.add_paragraph(f'Generated: {datetime.now().strftime("%B %d, %Y")}')
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    date_para.runs[0].font.size = Pt(10)

    doc.add_paragraph()

    # Stats row
    compression = round((1 - summary_word_count / original_word_count) * 100)
    stats_para = doc.add_paragraph()
    stats_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    stats_run = stats_para.add_run(
        f"Original: {original_word_count:,} words   |   "
        f"Summary: {summary_word_count:,} words   |   "
        f"Compression: {compression}%"
    )
    stats_run.font.size = Pt(10)
    stats_run.font.color.rgb = RGBColor(0x44, 0x60, 0x80)

    doc.add_paragraph()

    # Paragraph Summary
    h = doc.add_heading('Document Summary', level=1)
    h.runs[0].font.color.rgb = RGBColor(0x1a, 0x3a, 0x5c)
    p = doc.add_paragraph(paragraph)
    p.runs[0].font.size = Pt(11)
    p.paragraph_format.space_after = Pt(12)

    doc.add_paragraph()

    # Key Takeaways
    h2 = doc.add_heading('Key Takeaways', level=1)
    h2.runs[0].font.color.rgb = RGBColor(0x1a, 0x3a, 0x5c)
    for point in bullet_points:
        bp = doc.add_paragraph(style='List Bullet')
        run = bp.add_run(point)
        run.font.size = Pt(11)
        bp.paragraph_format.space_after = Pt(4)

    doc.add_paragraph()

    # Key Terms
    h3 = doc.add_heading('Key Terms', level=1)
    h3.runs[0].font.color.rgb = RGBColor(0x1a, 0x3a, 0x5c)
    terms = doc.add_paragraph()
    for i, (word, _) in enumerate(keywords):
        run = terms.add_run(word)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0x1a, 0x3a, 0x5c)
        run.font.size = Pt(10)
        if i < len(keywords) - 1:
            terms.add_run('  ·  ').font.size = Pt(10)

    doc.add_paragraph()
    footer_p = doc.add_paragraph('Generated by ScholarSum · Cambrian College NLP Capstone 2026')
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_p.runs[0].font.size = Pt(9)
    footer_p.runs[0].font.color.rgb = RGBColor(0xaa, 0xaa, 0xaa)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def export_pdf(bullet_points, paragraph, keywords, original_word_count, summary_word_count):
    """Generate a formatted PDF using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
    except ImportError:
        raise Exception("reportlab not installed. Run: pip install reportlab")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=25*mm, bottomMargin=20*mm
    )

    compression = round((1 - summary_word_count / original_word_count) * 100)
    styles = getSampleStyleSheet()

    DARK_BLUE = colors.HexColor("#1a3a5c")
    MID_BLUE  = colors.HexColor("#2563a8")
    LIGHT_BG  = colors.HexColor("#f0f4f9")
    BODY_COLOR = colors.HexColor("#1e2a3a")

    title_style = ParagraphStyle("Title", parent=styles["Title"],
        textColor=DARK_BLUE, fontSize=22, spaceAfter=2, alignment=TA_CENTER)
    subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"],
        textColor=MID_BLUE, fontSize=11, spaceAfter=2, alignment=TA_CENTER)
    date_style = ParagraphStyle("Date", parent=styles["Normal"],
        textColor=colors.HexColor("#888888"), fontSize=9, spaceAfter=10, alignment=TA_CENTER)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"],
        textColor=DARK_BLUE, fontSize=13, spaceBefore=14, spaceAfter=6,
        borderPad=4, backColor=LIGHT_BG, leftIndent=-4)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
        textColor=BODY_COLOR, fontSize=10, leading=16, spaceAfter=8, alignment=TA_JUSTIFY)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],
        textColor=BODY_COLOR, fontSize=10, leading=15, spaceAfter=5,
        leftIndent=16, bulletIndent=4, bulletFontName="Helvetica",
        bulletFontSize=14, bulletColor=MID_BLUE)
    kw_style = ParagraphStyle("KW", parent=styles["Normal"],
        textColor=DARK_BLUE, fontSize=9, leading=14, alignment=TA_CENTER)
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"],
        textColor=colors.HexColor("#aaaaaa"), fontSize=8, alignment=TA_CENTER)

    story = []

    # Header
    story.append(Paragraph("ScholarSum", title_style))
    story.append(Paragraph("Intelligent Academic Document Summary", subtitle_style))
    story.append(Paragraph(datetime.now().strftime("%B %d, %Y"), date_style))
    story.append(HRFlowable(width="100%", thickness=1, color=MID_BLUE, spaceAfter=10))

    # Stats table
    stats_data = [[
        Paragraph(f"<b>{original_word_count:,}</b><br/><font size=8 color=#6a7f99>Original words</font>", ParagraphStyle("s", alignment=TA_CENTER, fontSize=14, textColor=MID_BLUE)),
        Paragraph(f"<b>{summary_word_count:,}</b><br/><font size=8 color=#6a7f99>Summary words</font>", ParagraphStyle("s", alignment=TA_CENTER, fontSize=14, textColor=MID_BLUE)),
        Paragraph(f"<b>{compression}%</b><br/><font size=8 color=#6a7f99>Compression</font>", ParagraphStyle("s", alignment=TA_CENTER, fontSize=14, textColor=MID_BLUE)),
        Paragraph(f"<b>{len(bullet_points)}</b><br/><font size=8 color=#6a7f99>Key points</font>", ParagraphStyle("s", alignment=TA_CENTER, fontSize=14, textColor=MID_BLUE)),
    ]]
    t = Table(stats_data, colWidths=["25%","25%","25%","25%"])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), LIGHT_BG),
        ("ROUNDEDCORNERS", [6]),
        ("BOX", (0,0), (-1,-1), 0.5, colors.HexColor("#d0dae8")),
        ("INNERGRID", (0,0), (-1,-1), 0.5, colors.HexColor("#d0dae8")),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 14))

    # Paragraph summary
    story.append(Paragraph("Document Summary", section_style))
    story.append(Paragraph(paragraph.replace("&", "&amp;").replace("<", "&lt;"), body_style))
    story.append(Spacer(1, 8))

    # Key Takeaways
    story.append(Paragraph("Key Takeaways", section_style))
    for point in bullet_points:
        safe = point.replace("&", "&amp;").replace("<", "&lt;")
        story.append(Paragraph(f"• {safe}", bullet_style))
    story.append(Spacer(1, 8))

    # Key Terms
    story.append(Paragraph("Key Terms", section_style))
    terms = "   ·   ".join(w for w, _ in keywords)
    story.append(Paragraph(terms, kw_style))
    story.append(Spacer(1, 16))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd"), spaceAfter=6))
    story.append(Paragraph("Generated by ScholarSum · Cambrian College NLP Capstone 2026", footer_style))

    doc.build(story)
    buf.seek(0)
    return buf